istio-releases/pipeline

- rel_scripts/pipeline_parameters_lib.sh
- rel_scripts/run_daily_build.sh
- rel_scripts/run_daily_release.sh
- rel_scripts/run_monthly_build.sh
- rel_scripts/run_monthly_release.sh
- rel_scripts/trigger_daily_release.sh
- rel_scripts/trigger_daily_test.sh
- rel_scripts/trigger_monthly_release.sh
- rel_scripts/trigger_monthly_test.sh
> add parameters lib

- master/daily/build/build_parameters.sh
This is a generated PR that triggers release build, and will be automatically merged 
```release-note
none
```
> master-20181207-07-22 - Build

- daily/release_params.sh
> DAILY release-1.0-20181215-10-09

- daily/release_params.sh
> DAILY release-1.0-20181218-11-59

- daily/release_params.sh
> DAILY master-20181218-12-00

- daily/release_params.sh
> Create a new daily release for 1.1

- daily/release_params.sh
> DAILY release-1.1-20181219-12-58

- daily/release_params.sh
> DAILY release-1.0-20181220-13-02

- daily/release_params.sh
> DAILY master-20190115-16-14

- daily/release_params.sh
> DAILY release-1.1-20190123-18-55

- daily/release_params.sh
> DAILY release-1.1-20190124-10-02

- daily/release_params.sh
> DAILY release-1.1-20190124-15-51

- daily/release_params.sh
> DAILY release-1.1-20190124-18-26

- scripts/get_perf_tools.sh
The script will be part postsubmit test run after release is cut.
> Added script to get tools repo for perf testing

- monthly/release_params.sh
Building 1.1.5 to pick up a fix for https://github.com/istio/istio/issues/13717
istio/istio has not updated istio/api, so I didn't update istio/proxy
@utka please take a look
> Release 1.1.5

- daily/release_params.sh
Create a new build from the latest code with hash c9bcad4.
> Create a new build from the latest code with hash c9bcad4

- scripts/augmented_params.sh
- scripts/build_test_presubmit.sh
Adding a new Scripts to build first before running test.
This work is part of getting rid run_after_success.
> Adding a new Scripts to build first before running test.

- monthly/release_params.sh
> Build release 1.2.rc1

- monthly/release_params.sh
Reverts istio-releases/pipeline#1080
> Revert "Build release 1.2.5"

- daily/release_params.sh
Pinned to the operator update SHA-1
> Manual daily build

- monthly/release_params.sh
NB: some artefacts of this build might be manually replaced on 10/8
> Trigger a build on current release-1.2 of istio
